### ISSUE TITLE
Renaming default branch name from "master" to "main"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/compreffor#146]
The default branch in this repo is now called `main`. All open pull requests were automatically updated accordingly and `github.com` gives us this advice:

Your members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share these commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by anthrotype** [comment]
thanks felipe. I think github gives already enough notices (first time you visit a renamed project, or inside each PR a message pops up), so we don't also need to create issues like these on all the repository.
