### ISSUE TITLE
Fails to build with Cython 3

### ISSUE THREAD

**Issue by musicinmybrain** [googlefonts/compreffor#150]
Cython 3.0.0 was recently released, and `compreffor` is not compatible.

```
python3 -m build
```

```
[...]
running build_ext
building 'compreffor._compreffor' extension
error: unknown file type '.pyx' (from 'src/cython/_compreffor.pyx')

ERROR Backend subprocess exited when trying to invoke build_wheel
```

I will open a PR to pin `cython<3` for now, but it would be better to fix this properly.

**Comment by anthrotype** [comment]
thanks for reporting

> unknown file type '.pyx'

that's unexpected.. pyx _is_ the cython file extension 🤔

**Comment by musicinmybrain** [comment]
> that's unexpected.. pyx _is_ the cython file extension 🤔

I agree. My first guess would be that it is a weird side effect of the [reworking of `build_ext`](https://github.com/cython/cython/issues/3541), but I tried the obvious workaround of `from Cython.Distutils import old_build_ext as build_ext`, and that didn’t seem to help. I haven’t had a chance to look into it more closely.

**Comment by musicinmybrain** [comment]
According to https://github.com/cython/cython/issues/5305, https://github.com/libusb/hidapi has the same problem.
